In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [5]:
arr=np.array([1,2,3])
print (arr)

[1 2 3]


In [9]:
arr_2d=np.array(([1,2,3],[4,5,6]))
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Special Arrays

In [29]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
a=np.ones((2,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
a=np.ones((2,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
a=np.eye((3))
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [23]:
a=np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [28]:
a=np.random.randn(3,2)
print(a)

[[-0.28402142  0.54055166]
 [ 1.81550138  0.4565929 ]
 [ 1.39008186 -1.1755947 ]]


In [26]:
a=np.random.rand(3,2)
print(a)

[[0.98929514 0.45411592]
 [0.50403207 0.29362291]
 [0.9303864  0.28051362]]


In [ ]:
#Array Attributes

In [33]:
arr=np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [34]:
print(arr.shape)

(2, 3)


In [35]:
print(arr.ndim)

2


In [36]:
print(arr.size)

6


In [37]:
print(arr.dtype)

int64


In [38]:
#Array Operations
a=np.array([1,2,3])
b=np.array([4,5,6])

In [39]:
a+b

array([5, 7, 9])

In [40]:
b-a

array([3, 3, 3])

In [41]:
a*b

array([ 4, 10, 18])

In [42]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [43]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [44]:
#Matrix Multiplication
A=np.array([[1,2],[3,4]])

In [45]:
B=np.array([[5,6],[7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [46]:
A@B

array([[19, 22],
       [43, 50]])

In [51]:
#Aggregation
arr=np.array([1,2,3,4])
print(arr.sum())

10


In [54]:
print(arr.mean())

2.5


In [55]:
print(arr.min())

1


In [56]:
print(arr.max())

4


In [57]:
print(arr.std())

1.118033988749895


In [59]:
#indexing and slicing
#1D Array

In [61]:
arr=np.array([1,2,3,4,5])
print(arr[0])

1


In [62]:
print(arr[1:4])

[2 3 4]


In [63]:
print(arr[::2])

[1 3 5]


In [64]:
#2D arrays

In [67]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,1])

5


In [68]:
print(arr[:,1])

[2 5]


In [72]:
print(arr[1,:3])

[4 5 6]


In [73]:
#Boolean Indexing
arr=np.array([1,2,3,4,5])

In [76]:
mask=arr<3

In [77]:
print(arr[mask])

[1 2]


In [78]:
#Reshaping and Combining Arrays
#Reshape
arr=np.arange(6)

In [79]:
print(arr.reshape(2,3))

[[0 1 2]
 [3 4 5]]


In [82]:
#concatenation
a=np.array([1,2])
b=np.array([3,4])
np.concatenate((a,b))

array([1, 2, 3, 4])

In [83]:
#Stacking
np.vstack((a,b))

array([[1, 2],
       [3, 4]])

In [84]:
np.hstack((a,b))

array([1, 2, 3, 4])

In [85]:
a = np.array([1, 2, 3])
a + 5 

array([6, 7, 8])

In [87]:
# Save to a file
np.save('array.npy', arr)

In [ ]:
# Load from a file
loaded_arr = np.load('array.npy')